### ISSUE TITLE
Update FUNDING.yml

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/rhof-cli#22]
Change this file content https://github.com/arshadkazmi42/rhof-cli/blob/master/.github/FUNDING.yml

from 

```
patreon: arshadkazmi42
custom: https://arshadkazmi42.github.io
```

to 

```
github: arshadkazmi42
```

**Comment by cpalileo** [comment]
Thanks for giving us new guys some small tasks to get better acquainted with open source projects.
