### ISSUE TITLE
rhof-cli is not in npm registry

### ISSUE THREAD

**Issue by theNaut1lus** [arshadkazmi42/rhof-cli#9]
the command `npm i -g rhof-cli` no longer works with npm
probably because the package name was changed in npm registry

on querying the npm website it suggests `npm i @gh-conf/rhof`

seems like the documentation needs an update.
I can create a PR modifying and correcting the README.

**Comment by arshadkazmi42** [comment]
Actually name on npm registry is rhof. Its always been that. Somehow wrong name is added in readme. It's `npm i -g rhof` you can send a pr with this change is

**Comment by theNaut1lus** [comment]
Awesome @arshadkazmi42 please wait.

**Comment by theNaut1lus** [comment]
@arshadkazmi42  Although I will suggest a go through of the whole readme to ensure that everything is in order
